### ISSUE TITLE
CheatSheet.pdf is a HTML file

### ISSUE THREAD

**Issue by heikkil** [alhassy/ElispCheatSheet#1]

**Comment by alhassy** [comment]
Hey, thanks for the issue; but I'm not sure what the problem is. Please elaborate.

Are you saying, you would prefer that when one clicks on the PDF cheat sheet reference, then the PDF is opened rather than redirecting to the HTML that contains the PDF?

**Comment by novoid** [comment]
@alhassy https://github.com/alhassy/ElispCheatSheet/blob/master/CheatSheet.pdf returns "Sorry, this file is invalid so it cannot be displayed." in my Firefox browser. Maybe this is the referred issue?

However, when I click on "Download" (beneath "History") I get a perfectly fine PDF file.

So, @heikkil, is this the issue you are having?

**Comment by alhassy** [comment]
I've changed the url to be relative rather than absolute. Moreover, I've created the following webpage in case this issue exists for other setups: https://alhassy.github.io/ElispCheatSheet/ 

Please let me know if there are futher issues!

**Comment by heikkil** [comment]
I still have an issue with this. 

In your readme, you have text:

The listing sheet, as PDF, can be found here, while below is an unruly html rendition.

The word 'here' is a link to https://github.com/alhassy/ElispCheatSheet/blob/master/CheatSheet.pdf 

So when I see that link string ends with .pdf, I control click the link and do Save Link As... The Mac OS then downloads the linked file and saves it as CheatSheet.pdf but the contents is HTML text.

Instead, you could link directly to 
https://github.com/alhassy/ElispCheatSheet/raw/master/CheatSheet.pdf
and the link would take the user directly to the right file.

P.S. The file should have a better name that tells which cheat sheet the file is, e.g. ElispCheatSheet.pdf. Alternatively, you could make releases from your github project. That approach has the advantage that each release file could include a version number, e.g. ElispCheatSheet_v0.5.pdf that would help users to tell updated versions from outdated.

**Comment by alhassy** [comment]
Thanks for the great suggestions!

**Comment by alhassy** [comment]
I had it as a absolute link before, see above, and it seems the change to relative does not work on the mac. @heikkil  I recommend the following alternatives, [Tried & Worked on Mac OS]:

1. Click on "save as" at the GitHub page I've since provided: https://alhassy.github.io/ElispCheatSheet/

     Afaik, this approach works on all browsers, and so I'll place a link to this page on the readme page.

2. Click on the "here" link, which takes you to the PDF then press the "Download" button. As @novoid suggests.

Regarding the idea of releases; that may be a good idea and I think I will definitely pursue it. For now, the cheat sheets automatically contain the date of the most recent alteration and so there is little worry about being out of date, perhaps.

All the best,

Musa
